query discussPostItems($orderBy: ArticleOrderByEnum, $keywords: [String]!, $tagSlugs: [String!], $skip: Int, $first: Int) {
  ugcArticleDiscussionArticles(
    orderBy: $orderBy # HOT, MOST_VOTES, MOST_RECENT
    keywords: $keywords
    tagSlugs: $tagSlugs
    skip: $skip
    first: $first
  ) {
    totalNum
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        uuid
        title
        slug
        summary
        author {
          realName
          userAvatar
          userSlug
          userName
          nameColor
          certificationLevel
          activeBadge {
            icon
            displayName
          }
        }
        isOwner
        isAnonymous
        isSerialized
        scoreInfo {
          scoreCoefficient
        }
        articleType
        thumbnail
        summary
        createdAt
        updatedAt
        status
        isLeetcode
        canSee
        canEdit
        isMyFavorite
        myReactionType
        topicId
        hitCount
        reactions {
          count
          reactionType
        }
        tags {
          name
          slug
          tagType
        }
        topic {
          id
          topLevelCommentCount
        }
      }
    }
  }
}
